// Automatically generated by astro-icon
// 2c3a7dcffd5e872d6fb2cf7cb7662702d2b60e8ac99159646fed277f294de7b6

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "apple_podcast"
		| "chat"
		| "close"
		| "deezer"
		| "google_podcast"
		| "headset"
		| "home"
		| "ig"
		| "joystick"
		| "logo_desktop"
		| "logo_mobile"
		| "menu_sandwich"
		| "play"
		| "soundcloud"
		| "spotfy"
		| "x"
		| "youtube";
}