// Automatically generated by astro-icon
// 672252c86ceae4c5494719036dbf72db39a24a6e58f7779067115d989395d48f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "apple_podcast"
		| "chat"
		| "close"
		| "deezer"
		| "google_podcast"
		| "headset"
		| "home"
		| "ig"
		| "joystick"
		| "linkedin"
		| "logo_desktop"
		| "logo_mobile"
		| "menu_sandwich"
		| "play"
		| "soundcloud"
		| "spotfy"
		| "youtube";
}