// Automatically generated by astro-icon
// f157118611edcf81da8b6b9c99ae8e587d76f381ddc32c5f412023d900c8a7f2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "chat"
		| "headset"
		| "home"
		| "ig"
		| "joystick"
		| "logo_desktop"
		| "logo_mobile"
		| "spotfy"
		| "x"
		| "youtube";
}